version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./api:/app
      - ./api/instance:/app/instance
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
